---
title: "Estudio de datos biométricos sobre Lucanus Cervus"
author: 
- Marcelo Atanasio Domínguez Mateo
- Arminda García Moreno
- Alejandro García Prada

date: today
format: 
  html:
    toc: true
    theme: cosmo
  pdf:
    documentclass: article
    number-sections: true
    titlepage: false
    toc-location: before-body
    include-in-header: _extensions/tocdots/tocdots.tex
    toc: true
    toc-title: "Índice"
    geometry:
      - margin=25mm
execute:
  warning: false
  echo: true
---
```{r, echo=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(psych)
library(summarytools)
library(knitr)
library(kableExtra)
```


```{r, echo=FALSE}
lab <- read.table(file = "data/lucanus.csv", header = TRUE, fill = TRUE)

lab <- lab |>
  mutate(
      KB = as.numeric(gsub(",", ".", trimws(KB))),
      EL = as.numeric(gsub(",", ".", trimws(EL))),
      SEXO = as.factor(trimws(SEXO)),
      PROVINCIA = ifelse(trimws(PROVINCIA) == "", "Otras", trimws(PROVINCIA)),
      PROVINCIA = as.factor(trimws(PROVINCIA))
  )

summary(lab)
```

```{r, echo=FALSE}
df <- lab |> 
  slice_sample(n = 150, replace = FALSE)
summary(df)
```

```{r, echo=FALSE}
summary(df$KB)
```

```{r, echo=FALSE}
  ggplot(df, aes(x = KB)) +
    geom_histogram(binwidth = 0.5, fill = "skyblue",color = "black") +
    labs(title = "Head Width Distribution",
         x = "Head Width (KB)",
         y = "Frequency")
```

```{r, echo=FALSE}
ggplot(df, aes(y = KB)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  labs(title = "Boxplot de Head Width",
       y = "Head Width (KB)")
```

## Comparación de la Cabeza entre las Provincias
Se agrupan los valores de KB en su parte entera para mejor legibilidad de los datos
```{r, echo=FALSE}
lab$KB_int <- floor(lab$KB)
pastel_colors <- c(
  "#E0F7FF", "#D1F0FF", "#C2E9FF", "#B3E2FF", "#A4DBFF", "#95D4FF", "#86CDFF", "#77C6FF", "#68BFFF", "#59B8FF", "#4AAFFF", "#3BA8FF", "#2CA1FF", "#1D9AFF", "#0E93FF", "#008CFF", "#007FCC", "#0073A6"
)
```

```{r, echo=FALSE}
tabla_contingencia <- summarytools::ctable(lab$KB_int, lab$PROVINCIA)
tabla_contingencia
```

```{r, echo=FALSE}
lab |>
  ggplot(aes(x = PROVINCIA, fill = factor(KB_int))) +
  geom_bar(position = position_dodge(), color = "black") +
  scale_fill_manual(values = pastel_colors) +
  theme_bw() +
  labs(
    x = "Province",          
    y = "Count",             
    fill = "KB Value"    
  )
```


```{r, echo=FALSE}
lab |>
  ggplot(aes(x = PROVINCIA, y = KB, fill = PROVINCIA)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(width = 0.2, size = 2, alpha = 0.3) +
  scale_fill_manual(values = pastel_colors[c(4,8,12)]) +
  theme_bw() +
  labs(
    x = "Province",
    y = "Head Width (KB)",
    title = "Comparison of head width between provinces",
    fill = "Province"
  )
```
La línea negra representa la mediana de los datos

```{r, echo=FALSE}
ggplot(lab, aes(x = PROVINCIA, y = KB_int, fill = PROVINCIA)) +
  geom_violin(trim = FALSE, color = "black", alpha = 0.6) + 
  geom_jitter(width = 0.15, size = 1.5, alpha = 0.3, color = "black") +  # points
  scale_fill_manual(values = pastel_colors[c(4,8,12)]) +
  theme_bw() +
  labs(
    x = "Province",
    y = "Head Width (KB)",
    title = "Violin Plot of KB by Province",
    fill = "Province"
  )

```

```{r, echo=FALSE}
with(
  df, 
  stby(
    KB, 
    PROVINCIA, 
    descr
  )
)
```


## Comparar la anchura de la cabeza de las hembras con la de los machos.
```{r, echo=FALSE}
breaks <- seq(floor(min(df$KB)), ceiling(max(df$KB)), by = 1)

df_table <- df |> 
  mutate(KB_CLASS = cut(KB, breaks = breaks, include.lowest = TRUE))

freq_table <- table(df_table$KB_CLASS, df$SEXO)

percent_table <- round(prop.table(freq_table, margin = 2) * 100, 1)  # % per SEXO

combined <- matrix(
  paste0(freq_table, " (", percent_table, "%)"),
  nrow = nrow(freq_table),
  dimnames = dimnames(freq_table)
)

combined <- rbind(combined, Total = c(colSums(freq_table), sum(freq_table)))

# Crear tabla con kable y kableExtra
kable(combined, 
      caption = "Frequency and Percentage of Head Width by Sex (1-unit bins)", 
      align = "c", 
      format = "html") |> 
  kable_styling(full_width = FALSE, bootstrap_options = c("striped", "hover", "condensed", "responsive")) |> 
  row_spec(0, bold = TRUE) |>
  row_spec(nrow(combined), bold = TRUE, background = "#F5F5F5") |> # Total gris claro
  column_spec(1:3, border_right = TRUE, width = "50mm") |> 
  kable_paper("hover", full_width = FALSE)
```

```{r, echo=FALSE}
ggplot(df, aes(x = SEXO, y = KB, fill = SEXO)) +
  geom_boxplot(color = "black") +
  geom_jitter(aes(col = SEXO), alpha = 0.2) +
  scale_fill_manual(values = c("pink", "skyblue")) +
  labs(title = "Comparison of Head Width by Sex",
       x = "Sex",
       y = "Head Width (KB)") +
  theme_minimal()
```

```{r, echo=FALSE}
ggplot(df, aes(x = SEXO, y = KB, fill = SEXO)) +
  geom_violin(color = "black") +
  geom_jitter(aes(col = SEXO), alpha = 0.2) +
  scale_fill_manual(values = c("pink", "skyblue")) +
  labs(title = "Comparison of Head Width by Sex",
       x = "Sex",
       y = "Head Width (KB)") +
  theme_minimal()
```

```{r, echo=FALSE}
ggplot(df, aes(x = KB, fill = SEXO)) +
  geom_histogram(alpha = 0.6, position = "identity", binwidth = 0.5, color = "black") +
  scale_fill_manual(values = c("pink", "skyblue")) +
  labs(title = "Headh Width Distribution by Sex",
       x = "Head Width (KB)",
       y = "Frequency") +
  theme_minimal()
```

```{r, echo=FALSE}
with(
  df, 
  stby(
    KB,
    SEXO,
    descr
  )
)
```
